package consts

const (
	COROUTINE_EVENT = 1 + iota
	TIMER_EVENT
	CALLATER_EVT
	ClOSE_EVQ_EVT

	//SESSION_ON_ACCEPT_EVENT
	//SESSION_ON_CLOSE_EVENT
	//NET_MSG_EVENT
	//GAME_DATA_RELOAD_EVENT
	//SNET_ON_DISCONNECT
	//SNET_ON_RECONNECT
)
